# Certificate for gpupoet.com and www.gpupoet.com
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gpupoet-com-tls
  namespace: gpupoet-prod
spec:
  secretName: gpupoet-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - gpupoet.com
    - www.gpupoet.com