apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-deployment.yaml
  - app-service.yaml
  - app-ingress.yaml
  - db-statefulset.yaml
  - db-service.yaml
  - searxng-deployment.yaml
  - searxng-service.yaml
  - searxng-configmap.yaml
  - mcp-gateway-deployment.yaml
  - mcp-gateway-service.yaml
