apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpupoet-www-redirect
  namespace: coinpoet-prod
  annotations:
    # to reference the middleware use:  <middleware-namespace>-<middleware-name>@kubernetescrd
    #   per https://doc.traefik.io/traefik/v2.2/middlewares/overview/#provider-namespace
    traefik.ingress.kubernetes.io/router.middlewares: coinpoet-prod-www-redirect@kubernetescrd
    # issue a cert with cert-manager for www.gpupoet.com
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  rules:
    - host: "www.gpupoet.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  name: web-ui
  tls: # TLS configuration using cert-manager
    - hosts:
        - "www.gpupoet.com"
      secretName: gpupoet-com-tls # Reuse existing certificate that covers both domains