apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./transmission
  - ./tayle
  - ./home-assistant
  - ./photoprism
  - ./monitoring
  - ./plex
  - ./scott-willeke-com
  - ./gpupoet
  - ./coinpoet-redirect
  - ./activescott-redirect
  - ./ramblefeed
  - ./oksana-willeke-redirect
  - ./tinkerbell
  - ./wordpress-micah-mmm
