# NOTE: We use ingress here rather than a simple service so we can route traffic
#   based on hostname and not only IP. Ingress also has the advantage of being
#   able to serve TLS.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    # to reference the middleware use:  <middleware-namespace>-<middleware-name>@kubernetescrd
    #   per https://doc.traefik.io/traefik/v2.2/middlewares/overview/#provider-namespace
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-prometheus-basic-auth@kubernetescrd
spec:
  tls:
  # The patches in kustomize are ugly here (the patch is basically the whole Ingress). This could probably be made cleaner using a configMap + configMapGenerator or something to grab these values from a simple property file or labels or something
  - hosts:
      - prometheus.activescott.com # e.g. photos.example.com
    secretName: prometheus-activescott-com-tls #e.g. cert-example-com
  rules:
  # don't forget to set this up in DNS
  - host: prometheus.activescott.com # e.g. photos.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Service created by the prometheus Helm chart
            name: prometheus-server
            port:
              number: 80
