apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        app.activescott.com/component: app
    spec:
      containers:
        - name: app
          # NOTE: this image is replaced with an images transformer in the overlay
          image: gpupoet-image-app

          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "0.6"
              memory: "0.6Gi"

          ports:
            - containerPort: 3000

          env:
            - name: POSTGRES_PRISMA_URL
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: POSTGRES_PRISMA_URL

            - name: POSTGRES_URL_NON_POOLING
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: POSTGRES_URL_NON_POOLING

            - name: PUBLIC_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: PUBLIC_DOMAIN

            - name: PUBLIC_POSTHOG_HOST
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: PUBLIC_POSTHOG_HOST

            - name: PUBLIC_POSTHOG_KEY
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: PUBLIC_POSTHOG_KEY

            - name: EBAY_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: EBAY_ENVIRONMENT

            - name: EBAY_AFFILIATE_CAMPAIGN_ID
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: EBAY_AFFILIATE_CAMPAIGN_ID

            - name: EBAY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: EBAY_CLIENT_ID

            - name: EBAY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: EBAY_CLIENT_SECRET

            - name: INDEXNOW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: INDEXNOW_API_KEY

            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: ADMIN_USERNAME

            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: ADMIN_PASSWORD

          readinessProbe:
            httpGet:
              path: /api/health/readiness
              port: 3000
            # next is a pig
            initialDelaySeconds: 40
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health/liveness
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 10
