# NOTE: We use ingress here rather than a simple service so we can route traffic
#   based on hostname and not only IP. Ingress also has the advantage of being
#   able to serve TLS.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpupoet-app-ingress
spec:
  # patched in kustomize for TLS in production
  rules:
    - host: gpupoet.com
      http:
        paths:
          # Block external access to internal ops endpoints
          - path: /ops/revalidate-cache
            pathType: Exact
            backend:
              service:
                name: nonexistent-service
                port:
                  number: 80
          - path: /ops/cleanup-listings
            pathType: Exact
            backend:
              service:
                name: nonexistent-service
                port:
                  number: 80

          # Allow all other traffic to the app
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                # port of the referenced service. A port name or port number is required for a IngressServiceBackend.
                port:
                  name: web-ui
