apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-deployment.yaml
  - app-service.yaml
  - app-ingress.yaml
  - db-deployment.yaml
  - db-service.yaml
  - cache-revalidation-job.yaml
  - cleanup-listings-job.yaml
  - indexnow-job.yaml
  - indexnow-pvc.yaml
