apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        app.activescott.com/component: app
    spec:
      containers:
        - name: app
          image: ramblefeed-image-app
          ports:
            - containerPort: 3200
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: DATABASE_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: JWT_SECRET
            - name: JWT_MAGIC_LINK_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: JWT_MAGIC_LINK_SECRET
            - name: E2E_MAGIC_LINK_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: E2E_MAGIC_LINK_SECRET
            - name: SNAPSHOT_STORAGE_DIR
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: SNAPSHOT_STORAGE_DIR
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: EMAIL_FROM
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: SMTP_PORT
            - name: SMTP_SECURE
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: SMTP_SECURE
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: SMTP_PASS
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: APP_URL
            - name: POSTHOG_KEY
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: POSTHOG_KEY
            - name: GITHUB_RELEASE_NOTES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: GITHUB_RELEASE_NOTES_TOKEN
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 3200
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 3200
            initialDelaySeconds: 10
            periodSeconds: 10
